//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int IdBill { get; set; }
        public double Ammount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> BillTableId { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
