//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contain
    {
        public int ContainsOfferId { get; set; }
        public int ContainsStockRoomId { get; set; }
        public int ContainsBarId { get; set; }
        public int ContainsDeliveryId { get; set; }
        public int ContainsOrderId { get; set; }
    
        public virtual Bar Bar { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Order Order { get; set; }
        public virtual StockRoom StockRoom { get; set; }
    }
}
